language: php
php:
  - 5.5
  - 5.4
  - hhvm

env:
  - DB_HOST="127.0.0.1" DB_NAME="codeception_test" DB_USERNAME="travis"

before_script:
  - composer install --dev --prefer-source --no-interaction
  - "mysql -e 'create database codeception_test;'"
  - php artisan migrate --no-interaction

script:
  - php vendor/bin/codecept run
  - php vendor/bin/codecept run functional

notifications:
  slack: informulate:Io7yxfri2SwOzQ0h3KUG4OFB
